server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ching-Chieh-Wang/config-repo
          skipSslValidation: true
          clone-on-start: true