server:
  port: 50013
spring:
  config:
    import : vault://
  application:
    name: config-service
  cloud:
    vault:
      authentication: TOKEN
      token : ${VAULT_TOKEN}
      scheme: http
      host: linux-076
      port: 50006
      fail-fast: true
      kv:
        default-context: config-service
        profiles:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          skipSslValidation: true
          clone-on-start: true
