server:
  port: 8888

spring:
  boot:
    admin:
      client:
        url: ${SPRING_ADMIN_URL}
        username: ${EUREKA_SERVER_USERNAME}
        password: ${EUREKA_SERVER_PASSWORD}
  config:
    import: optional:classpath:.env
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          skipSslValidation: true
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}