server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          skipSslValidation: true
          clone-on-start: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka
  instance:
    prefer-ip-address: false
    hostname: ${SERVER_HOST}
    secure-port-enabled: true
    non-secure-port-enabled: false
    home-page-url: https://${SERVER_HOST}
    health-check-url: https://${SERVER_HOST}/actuator/health
    status-page-url: https://${SERVER_HOST}/actuator/info
