server:
  port: 8888
spring:
  boot:
    admin:
      client:
        url: ${SERVER_URL}/admin
        username: ${SPRING_SECURITY_USERNAME}
        password: ${SPRING_SECURITY_PASSWORD}
  application:
    name: config-server

  cloud:
    config:
      username: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          skipSslValidation: true
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always