spring:
  application:
    name: product-write-service
  config:
    import:
      configserver:${CONFIG_SERVICE_URI}?name=product/product-write-service"
  cloud:
    config:
      token: ${VAULT_SERVICE_TOKEN}

