server:
  port: 8081
spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-listener-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
