spring:
  application:
    name: api-gateway-service
  config:
    import: configserver:${CONFIG_SERVICE_URI}
  cloud:
    config:
      token: ${VAULT_API_GATEWAY_SERVICE_TOKEN}
      fail-fast: true