spring:
  application:
    name: api-gateway-service
  config:
    import: configserver:http://linux-075:50013
  cloud:
    config:
      token: ${VAULT_API_GATEWAY_SERVICE_TOKEN}
      fail-fast: true