server:
  port: 50013
spring:
  config:
    import: vault://
  profiles:
    active: vault,git
  application:
    name: config-service
  cloud:
    vault:
      host: linux-076
      port: 50006
      scheme: http
      authentication: TOKEN
      token: ${VAULT_CONFIG_SERVICE_TOKEN}
      kv:
        profiles:
    config:
      server:
        vault:
          host: linux-076
          port: 50006
          kv-version: 2
          order: 1
          profile-separator: '?profile='
          path-to-key: application
        git:
          uri: https://github.com/Ching-Chieh-Wang/zwap-config-repo.git
          username: Ching-Chieh-Wang
          password: ${GIT_CONFIG_REPO_PASSWORD}
          order: 2

