server:
  port: 50013
spring:
  config:
    import: vault://
  profiles:
    active: vault,git
  application:
    name: config-service
  cloud:
    vault:
      host: ${VAULT_SERVICE_HOST}
      port: ${VAULT_SERVICE_PORT}
      scheme: http
      authentication: TOKEN
      token: ${VAULT_CONFIG_SERVICE_TOKEN}
      kv:
        profiles:
    config:
      server:
        vault:
          host: ${VAULT_SERVICE_HOST}
          port: ${VAULT_SERVICE_PORT}
          kv-version: 2
          order: 1
          profile-separator: '?profile='
          path-to-key: application
        git:
          uri: https://github.com/Ching-Chieh-Wang/zwap.git
          username: Ching-Chieh-Wang
          password: ${GIT_CONFIG_REPO_PASSWORD}
          searchPaths: "config-repo"
          order: 2

